### ISSUE TITLE
kuza13-sp1

### ISSUE THREAD

**Issue by andreukuznec** [nvbach91/4IZ268-2023-2024-ZS#152]
- [x] Zkrácena délka řádků textu v kontejnerech, aby se předešlo nadměrné šířce stránky.
- [ ] Přidána favicon ikona.
- [x] Zvýrazněna aktivní položka v navigaci.
- [ ] Implementován vícesloupcový layout.
- [x] Přidán atribut 'lang'.
- [x] Vloženy potřebné meta tagy.
- [ ] Přidán code meta tag.
- [x] Ujistěno, že samozavírací tagy neobsahují ukončovací lomítka.
- [x] Vytvořen footer.
- [ ] Upraven design pro tisk.
- [x] Použity media queries.
- [x] Obohacen obsah.

https://eso.vse.cz/~kuza13/sp1/

https://eso.vse.cz/~kuza13/sp1/about/

https://eso.vse.cz/~kuza13/sp1/practices/
https://eso.vse.cz/~kuza13/sp1/practices/#organic-farming
https://eso.vse.cz/~kuza13/sp1/practices/#crop-rotation
https://eso.vse.cz/~kuza13/sp1/practices/#precision-agriculture

https://eso.vse.cz/~kuza13/sp1/benefits/
https://eso.vse.cz/~kuza13/sp1/benefits/#healthy-soil
https://eso.vse.cz/~kuza13/sp1/benefits/#environmental-impact
https://eso.vse.cz/~kuza13/sp1/benefits/#economic-stability

https://eso.vse.cz/~kuza13/sp1/future/

**Comment by nvbach91** [comment]
- tisk musí být bez pozadí
- kde najdu zmíněný vícesloupcový layout?
- favicon není na všech stránkách

**Comment by andreukuznec** [comment]
- Opravil nastavení pro tisk
- Přidál vícesloupcový layout  
- Upravil zobrazení favicon

**Comment by nvbach91** [comment]
- nekonzistentní syntaxe HTML atributů
- nevalidní HTML (homepage)
- v kódu stále jsou ukončovací lomítka u nepárových tagů
- tisk má stále pozadí

**Comment by nvbach91** [comment]
https://github.com/nvbach91/4IZ268-2023-2024-ZS/issues/3
