### ISSUE TITLE
SP1 - mata29

### ISSUE THREAD

**Issue by alex-matejicek** [nvbach91/4IZ268-2023-2024-ZS#159]
Opravy přetékání a tisku.

HTML:
[https://eso.vse.cz/~mata29/sp1/home/](https://eso.vse.cz/~mata29/sp1/home/)
[https://eso.vse.cz/~mata29/sp1/about/](https://eso.vse.cz/~mata29/sp1/about/)
[https://eso.vse.cz/~mata29/sp1/showdates/](https://eso.vse.cz/~mata29/sp1/showdates/)
[https://eso.vse.cz/~mata29/sp1/discography/](https://eso.vse.cz/~mata29/sp1/discography/)
[https://eso.vse.cz/~mata29/sp1/blog/](https://eso.vse.cz/~mata29/sp1/blog/)
[https://eso.vse.cz/~mata29/sp1/new-ep/](https://eso.vse.cz/~mata29/sp1/new-ep/)
[https://eso.vse.cz/~mata29/sp1/belgian-blue/](https://eso.vse.cz/~mata29/sp1/belgian-blue/)
[https://eso.vse.cz/~mata29/sp1/bramborohrani/](https://eso.vse.cz/~mata29/sp1/bramborohrani/)
[https://eso.vse.cz/~mata29/sp1/banat/](https://eso.vse.cz/~mata29/sp1/banat/)
[https://eso.vse.cz/~mata29/sp1/rande-s-revizorem/](https://eso.vse.cz/~mata29/sp1/rande-s-revizorem/)

CSS:
[https://eso.vse.cz/~mata29/sp1/styles/about_style.css](https://eso.vse.cz/~mata29/sp1/styles/about_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/albumpage_style.css](https://eso.vse.cz/~mata29/sp1/styles/albumpage_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/blog_style.css](https://eso.vse.cz/~mata29/sp1/styles/blog_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/discography_style.css](https://eso.vse.cz/~mata29/sp1/styles/discography_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/glob_style.css](https://eso.vse.cz/~mata29/sp1/styles/glob_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/home_style.css](https://eso.vse.cz/~mata29/sp1/styles/home_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/nav_style.css](https://eso.vse.cz/~mata29/sp1/styles/nav_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/printed_style.css](https://eso.vse.cz/~mata29/sp1/styles/printed_style.css)
[https://eso.vse.cz/~mata29/sp1/styles/showdates_style.css](https://eso.vse.cz/~mata29/sp1/styles/showdates_style.css)

**Comment by nvbach91** [comment]
https://github.com/nvbach91/4IZ268-2023-2024-ZS/issues/3
