### ISSUE TITLE
kuzd02-sp1

### ISSUE THREAD

**Issue by diaDdi** [nvbach91/4IZ268-2023-2024-ZS#194]
[+] - kontrast písma na světlém pozadí
[+] - omezena délka řádky textu (kontejneru), aby nezabíraly zbytečně moc do šířky stránky 
[+] - kazda stranka je jeden soubor s nazvem index.html, nazev stranky je nazev obsahujici slozky
[+] - hodnoty atributu href tagu <a> v navigaci ne obsahují část index.html
[+] -  text-align: left místo justify u úzkých odstavců
[+] - zvýrazněna aktivní položka navigace
[+] - vhodné textové pasáže (ne tiskacím)
[+] - ne chybí mailto:
[+] -  přidán layout (např. obrázky, text)
[+] - přidány meta tagy (description, keywords)
[+] - v <title> ne chybí název webu
[+] - tisk musí být bez pozadí (Při tisku se pozadí původně nezobrazovalo, ale pro jistotu přidala jsem do kódu, aby se vypnulo. Pokud v tom pozadí bude potřeba, můžete jej zapnout v nastavení tisku.)
[+] - nedostatečné přizpůsobení pro tisk (Také jsem přidala několik podmínek, abych to zlepšit. Třeba to pozadí, font-size..:))
[+] - přidala jsem odkaz na Home do loga

Děkuji.

https://eso.vse.cz/~kuzd02/sp1/
https://eso.vse.cz/~kuzd02/sp1/attract/
https://eso.vse.cz/~kuzd02/sp1/tips/
https://eso.vse.cz/~kuzd02/sp1/traditions/
https://eso.vse.cz/~kuzd02/sp1/accommodations/

https://eso.vse.cz/~kuzd02/sp1/assets/css/style.css

**Comment by nvbach91** [comment]
Vím, že se to pozadí dá vypnout, ale to nemusí vědět Vaši čtenáři. Takže pro jistotu to vypnout, ale to se Vám ještě nepodařilo udělat.

![image](https://github.com/nvbach91/4IZ268-2023-2024-ZS/assets/20724910/10f8e095-40d3-498e-a8c2-b7241ac2de19)

Další doporučení:
- na některých místech je vhodnější text-align: left místo justify, zejména u úzkých odstavců
- na menším rozlišení obrazovky chybí vnitřní ohraničení, aby text nebyl hned ne okraji obrazovky
- na homepage je i ve Vašem případě vhodné uvést alespoň nějaký uvítací text, např. o čem je web a kam dál
