### ISSUE TITLE
mati04-sp1

### ISSUE THREAD

**Issue by IvanMatys** [nvbach91/4IZ268-2023-2024-ZS#211]
Dobrý večer,
https://eso.vse.cz/~mati04/sp1/index.html
https://eso.vse.cz/~mati04/sp1/about/index.html
https://eso.vse.cz/~mati04/sp1/contact/index.html
https://eso.vse.cz/~mati04/sp1/sources/index.html
https://eso.vse.cz/~mati04/sp1/study/index.html
https://eso.vse.cz/~mati04/sp1/study/basic_commands/index.html
https://eso.vse.cz/~mati04/sp1/study/text_filters/index.html
https://eso.vse.cz/~mati04/sp1/study/linux_distributions/index.html
https://eso.vse.cz/~mati04/sp1/study/permissions/index.html
https://eso.vse.cz/~mati04/sp1/css/style.css

Problémy - Opravy:
- tisk musi bez pozadi - opraveno, již je print bez pozadí

- zvýraznit aktivní položky menu i v podstránkách - opraveno, když jdu například na stránku "Permissions", tak je také zvýrazněna záložka "Study"

- chybí vícesloupcový layout - Přidán Grid layout do záložky "About me" + přidát flex layouty a jeden grid layout do "Text Filters"

- odkazy na externí stránky otevřít v nové záložce - opraveno, všechny externí odkazy se otevírají na nové stránce

- přidat odkaz na podstránky na stránce Study (rozcestník) - rozcestník do záložky "Study" byl přidán

- chybí identifikace webu v každé stránce (název, logo, ...) - Název byl vložen do identifikace každé stránky (LinuxTeach - xxx) + do nadpisu každé stránky

- v <title> chybí název webu - Byl vymyslen název LinuxTeach a vložen do <title>

**Comment by nvbach91** [comment]
zkuste tomuhle 
![image](https://github.com/nvbach91/4IZ268-2023-2024-ZS/assets/20724910/a8afaab2-157f-44aa-9c62-4bf5be7552ac)
nastavit css `position: fixed; top: 10px; left: 10px`
