### ISSUE TITLE
cerj37-sp1

### ISSUE THREAD

**Issue by JendaCerny** [nvbach91/4IZ268-2023-2024-ZS#223]
HTML:
https://eso.vse.cz/~cerj37/sp1/
https://eso.vse.cz/~cerj37/sp1/produkty/
https://eso.vse.cz/~cerj37/sp1/prodejny/
https://eso.vse.cz/~cerj37/sp1/zam/
https://eso.vse.cz/~cerj37/sp1/recepty/
https://eso.vse.cz/~cerj37/sp1/job-email/
CSS:
https://eso.vse.cz/~cerj37/sp1/css/style.css
https://eso.vse.cz/~cerj37/sp1/css/style_produkt.css
https://eso.vse.cz/~cerj37/sp1/css/style_prod.css
https://eso.vse.cz/~cerj37/sp1/css/style_zam.css
https://eso.vse.cz/~cerj37/sp1/css/style_rec.css
https://eso.vse.cz/~cerj37/sp1/css/style_mail.css

- [x] omezit délku řádky textu (kontejneru), aby nezabíraly zbytečně moc do šířky stránky
- [x] obrázky nejsou stažené a optimalizované
- [x] přidat odkaz na Home do loga
- [x] odkazy na externí stránky otevřít v nové záložce
- [x] css soubor dejte do složky css
- [x] obrázky ukládejte v jednom adresáři zvlášť
- [x] duplicitní CSS pravidla v rámci webu
- [x] chybí meta tagy
- [x] nepoužívat inline CSS
- [x] v CSS je odkaz na neexistující resource
- [x] hodnota atributu lang neodpovídá jazyku obsahu
- [x] formulář není form?
- [x] chybí přizpůsobení pro tisk
- [x] nevalidní HTML

**Comment by nvbach91** [comment]
duplicitní CSS pravidla v rámci webu neopraveno
