### ISSUE TITLE
kond12-sp1

### ISSUE THREAD

**Issue by DYKonkov** [nvbach91/4IZ268-2023-2024-ZS#228]
https://eso.vse.cz/~kond12/sp1/
https://eso.vse.cz/~kond12/sp1/anime/
https://eso.vse.cz/~kond12/sp1/manga/
https://eso.vse.cz/~kond12/sp1/character/index.html
https://eso.vse.cz/~kond12/sp1/technic/index.html

https://eso.vse.cz/~kond12/sp1/css/style.css

opraveno 
- obsah přetéká při nižším rozlšení
- navigace se zobrazuje bez pozadí a splývá s obsahem
- hodnoty atributu href tagu <a> nesmí obsahovat část index.html
- není všechny texty zarovnat na střed
- footer
-  sémantické tagy
-  přizpůsobení pro tisk
- zdeformované obrázky
- nevalidní HTML
- kód formátován

**Comment by nvbach91** [comment]
- navigace se zobrazuje bez pozadí a splývá s obsahem
- sémantické tagy
- tisk musi byt bez pozadi
- zdeformované obrázky
- nevalidní HTML (DOCTYPE)
