### ISSUE TITLE
pavj16-sp1

### ISSUE THREAD

**Issue by jan-pavek** [nvbach91/4IZ268-2023-2024-ZS#232]
Dobrý večer, posílám opravenou verzi statického webu.
https://eso.vse.cz/~pavj16/sp1opr/home/index.html
https://eso.vse.cz/~pavj16/sp1opr/menu/index.html
https://eso.vse.cz/~pavj16/sp1opr/delivers/index.html
https://eso.vse.cz/~pavj16/sp1opr/rewards/index.html
https://eso.vse.cz/~pavj16/sp1opr/about-us/index.html

https://eso.vse.cz/~pavj16/sp1opr/css/style.css

Byly opraveny následující chyby:
- top panel horizontálně přetéká
- na některých místech je vhodnější text-align: left místo justify, zejména u úzkých odstavců
- CSS font-family ukazuje na neexistující font
- odkazy na externí stránky otevřít v nové záložce
- kazda stranka musi byt jeden soubor s nazvem index.html, nazev stranky je nazev obsahujici slozky, nikoliv nazev souboru
- obrázky ukládejte do jednoho adresáře zvlášť
- chybí meta tagy
- použít HTML entity
- h1 se smí vyskytovat pouze jednou v rámci HTML dokumentu
- font je lepší importovat přes <link>
- tisk stránky about-us
- některé obrázky nejsou optimalizované

**Comment by nvbach91** [comment]
- stále přetéká top panel
- v atributech `src` elementu `<a>` nepíšeme část `index.html`
- odkazy na externí stránky otevřít v nové záložce
- hodnoty meta tagu description a keywords neodpovídají / nepopisují obsah webu
- tisk musí být bez pozadí
