### ISSUE TITLE
hujl00-sp1

### ISSUE THREAD

**Issue by LucieH22** [nvbach91/4IZ268-2023-2024-ZS#234]
- chybí zvýraznění aktivní položky navigace - doplněno
- proč není aktivní položka navigace vůbec vidět? - doplněno
- na některých místech je vhodnější text-align: left místo justify, zejména u úzkých odstavců - opraveno
- tisk musi bez pozadí - opraveno
- fotografile je lepší zobrazovat v jiném layoutu než lineárním jednosloupcovým - opraveno
- chybí meta tagy - doplněno

https://eso.vse.cz/~hujl00/sp1/index.html
https://eso.vse.cz/~hujl00/sp1/history/index.html
https://eso.vse.cz/~hujl00/sp1/culture/index.html
https://eso.vse.cz/~hujl00/sp1/monuments/index.html
https://eso.vse.cz/~hujl00/sp1/spa/index.html
https://eso.vse.cz/~hujl00/sp1/photographs/index.html
https://eso.vse.cz/~hujl00/sp1/css/style.css

**Comment by nvbach91** [comment]
- tisk musi bez pozadí - neopraveno
- chybny odkaz "o městě" v domovské stránce
