### ISSUE TITLE
pist02-sp1

### ISSUE THREAD

**Issue by tomaspiskule** [nvbach91/4IZ268-2023-2024-ZS#241]
Dobrý den, 
odevzdávám opravenou sp1:

https://eso.vse.cz/~pist02/sp1/
https://eso.vse.cz/~pist02/sp1/o-nas.html
https://eso.vse.cz/~pist02/sp1/reference.html
https://eso.vse.cz/~pist02/sp1/kontakt.html
https://eso.vse.cz/~pist02/sp1/dalsi-sluzby.html
https://eso.vse.cz/~pist02/sp1/pronajem.html
https://eso.vse.cz/~pist02/sp1/styles/style.css

Opravy:
- kazda stranka musi byt jeden soubor s nazvem index.html, nazev stranky je nazev obsahujici slozky, nikoliv nazev souboru
Komplet předěláno, podstránky jsou ve vlastních složkách, všechny href, img a další části závislé na struktuře složek přepsány a funkční. 

- chybí mailto: a tel:
Chybělo nedopatřením, odevzdal jsem verzi kde nebylo - v opravě doplněno. 

- některé obrázky nejsou optimalizované
Oba nezoptimalizované obrázky optimalizovány.

- chybí meta keywords
Nedával jsem, protože moderní SEO je nebere do úvahy (vyjádření googlu), ale v opravě jsem dodal. 

- dodržet správnou strukturu `<table>`
Přidáno `<thead>` a `<tbody>` (<tfoot> se do mé jediné tabulky nehodí).

- nepoužívat inline CSS
Oba případy odstraněny a přeneseny do .css

- používat HTML entity
Copyright přepsán na html entitu.

- nevalidní HTML
Opraveno - https://validator.w3.org/ nyní všechny části zelené.

- tisknout bez pozadí
Opraveno. 

- zvětšit klikatelný prostor kolem navigačních odkazů
Upraveno. 

- pozdní odevzdání
Odevzdání proběhlo podle komentáře v SP1 odevzdání i nahrání na eso včas - před půlnocí deadlinu.
Ale nyní odevzdání opravy tedy odevzdávám méně než 24h před obhajobou - omlouvám se, zasekl jsem se na hloupé chybě při předělání složkové struktury (v hlavním indexu jsem měl ../ místo ./ a dlouho nemohl přijít kde je chyba)

**Comment by nvbach91** [comment]
Ty odkazy co jste sem vlozil doufam uz neplati

**Comment by tomaspiskule** [comment]
Opraveno na validní odkazy
