### ISSUE TITLE
mati04 - SP2 dotaz

### ISSUE THREAD

**Issue by IvanMatys** [nvbach91/4IZ268-2023-2024-ZS#248]
Dobrý den,

při vypracování SP2 jsem narazil na problém s posíláním notifikací. V mé aplikaci měla dle zadání být funkce že si uživatel bude moct nastavit notifikaci na jisté datum a čas. Ale posléze jsem si našel že notifikaci, kterou se spouští časově nedělá přímo prohlížeč ale server.

Mohl bych na toto téma s vámi poprosit o konzultaci? Či jestli se můžu zeptat zda můžu danou funkci vynechat a udělat místo ní například nějakou jinou funkci.

Obhajobu mám 19.1 od 9:15.

**Comment by nvbach91** [comment]
Samozřejmě to potřebuje backend, ale ten si nemusíte implementovat, protože těch už je na internetu hodně, tj. stačí si nějaký najít a použít. Práce s posíláním notifikací pak bude podobná integraci aplikace s externí REST API. DOporučuji např. službu OneSignal, kde jsou k dispozici i návody.
