### ISSUE TITLE
Dotaz k požadavkům SP2

### ISSUE THREAD

**Issue by MustardFez** [nvbach91/4IZ268-2023-2024-ZS#260]
Dobrý den. Mám dotaz k upřesnění pár častých chyb uvedených v zadání SP2.

Aktualizace DOM v cyklu - je zde myšleno to, abychom konečné úpravy DOMu promítly na stránku najednou a nevykreslovaly jednotlivé elementy po jednom?

Používání funkce Alert - nemáme používat vůbec? (momentálně pomocí alertu upozorňuju uživatele na špatné vyplnění inputů).

**Comment by nvbach91** [comment]
1. jinými slovy:
  - nemodifikovat DOM v cyklu
  - v cyklu se nesmí vyskytovat žádné volání funkcí nebo příkazů, které přímo zasahují do obsahu DOM
2. funkce `alert()` funguje tak, že zastaví kód v místě jeho volání, takže spíše nepoužívat, používejte např. knihovnu `sweetalert2`
