### ISSUE TITLE
ruzo03 - SP2

### ISSUE THREAD

**Issue by ruzo03** [nvbach91/4IZ268-2023-2024-ZS#276]
Nahrál jsem nový návrh projektu přes Google Forms, nahrál jsem zároveň projekt na GitHub. 
Mohu poprosit o nějakou validaci toho projektu a případně potvrzení, že můžu přijít na obhajobu.

**Comment by nvbach91** [comment]
Dobrý den, Váš návrh nelze schválit, protože v něm chybí práce s externím REST API pro asynchronní načítání nebo posílání dat. V pokynech najdete příklady REST API, ze kterých si můžete bvybrat
