### ISSUE TITLE
ruzo03-SP2

### ISSUE THREAD

**Issue by ruzo03** [nvbach91/4IZ268-2023-2024-ZS#279]
Dobrý den, chtěl bych poprosit o schválení návrhu na SP2. Odeslal jsem nový Google formulář. Snad by to mělo už být vše v pořádku.

Děkuji

**Comment by nvbach91** [comment]
k Vašemu návrhu se bude hodit ještě použití localStorage pro ukládání a správu receptů. můžete si vymyslet strukturu dat takto:
  - recipeLists - seznamy receptů
  - recipes - recepty

tj. hledat recepty několika způsoby (free-text search, search podle ingredience, ...) a umožnit uživatelům vrácené výsledky vybírat a ukládat do seznamů a spravovat je v prohlížeči.

**Comment by ruzo03** [comment]
Dobrý den, splnil jsem všechny prerekvizity. Můžu přijít 2.2. na obhajobu, i když nejsem přihlášený ?

**Comment by nvbach91** [comment]
viz https://github.com/nvbach91/4IZ268-2023-2024-ZS/pull/284
