### ISSUE TITLE
Odevzdání sp2

### ISSUE THREAD

**Issue by hjgdtuesac** [nvbach91/4IZ268-2023-2024-ZS#289]
Dobrý den,
cirka týden zpět jsem se Vás na Teamsech psal zdali by bylo možné se dostat na některý z termínů 2.2., protože již všechny i ty předešlé byly zaplněné. Bohužel jsem v tu dobu neměl ještě splněné prerekvizity a tak jsem se až dnes ráno pokoušel vložit již hotový kód a zároveň Vás kontaktovat, ale do repozitáře bohužel nemám právo nahrávat. Bylo by i tak možné se zítřejší obhajoby účastnit a případně jak bych měl prosím v tuto chvíli postupovat?
S přáním hezkého dne, Fejtek.

**Comment by hjgdtuesac** [comment]
Github moc nepoužívám, tak Vás pro jistotu ještě tagnu, aby se to k Vám vůbec dostalo. @nvbach91

**Comment by nvbach91** [comment]
Moc si pohravate s predmetem pane kolego, nevim jestli to umite ale vykaslat se na pravidla hry se vam urcite nevyplati
