### ISSUE TITLE
mikj18-sp1

### ISSUE THREAD

**Issue by mikjin** [nvbach91/4IZ268-2023-2024-ZS#298]
https://eso.vse.cz/~mikj18/SP1/
https://eso.vse.cz/~mikj18/SP1/Kontakt/
https://eso.vse.cz/~mikj18/SP1/Na_objednavku/
https://eso.vse.cz/~mikj18/SP1/Novinky/
https://eso.vse.cz/~mikj18/SP1/Odvoz/
https://eso.vse.cz/~mikj18/SP1/Vyprodej/

staré chyby: 
 - špatná hodnota atributu lang - změněno na html lang="cs-CZ"
- názvy složek by neměly obsahovat diakritiku - už neosahují
- homepage index.html nedávat do podsložky ale přímo do kořene webu - done
- nekonzistentní layout produktů (ceny a názvy lítají všude) - dal jse m je do tabulky a drží na místě
- stránka Odvoz nemá zvýrazněnou aktivní položku navigaci - už má
- chybí mailto: a tel: - to jsem trochu nepochopil, udělal jsem to z toho <a> pro otevření v aplikaci
- zachovat název webu i na verzi pro tisk - h1 už tam je, tak jsem to pochopi
- chybí meta tagy - tím si také nejsem jistý
- 404 not found u script.js - script funguje
- chybí favicon - je tam, h v kroužku
- chybí identifikace stránky v title - každá stránka má vlastní title

**Comment by nvbach91** [comment]
HTML neni validni..
