### ISSUE TITLE
Termín odevzdání 1. SP

### ISSUE THREAD

**Issue by danieladam2001** [nvbach91/4IZ268-2023-2024-ZS#81]
Dobrý den,

chtěl jsem se zeptat, jestli odevzdání 1. semestrální práce má deadline na konci 9. týdne výuky, nebo 11. týdne. Na různých zdrojích se tyto informace liší.
https://github.com/nvbach91/4IZ268-2023-2024-ZS/wiki/P-Pokyny-SP1
https://4iz268.github.io/zakonceni/stranky/

Předem děkuji.

S pozdravem,
Daniel Adam

**Comment by nvbach91** [comment]
Dobrý den, platí termín 11. týden.
